### ISSUE TITLE
seems to be pulling in xtra styles

### ISSUE THREAD

**Issue by brandonmp** [bskimball/gatsby-plugin-antd#1]
using example of `import {Button} from 'antd'` results in tons of xtra css in the page, incl. all the antd font styles etc. 

I'm not sure if this is just how antd works even with modular imports, but to fix it i had to use 

```
import Button from 'antd/lib/Button';
import 'antd/lib/button/style/index.css';
```

^^ this results in a mostly clean bundle

**Comment by bskimball** [comment]
That's how antd pulls in the other styles. It will always pull in the base styles, even if you are just using the button. If you want only the button styles then the code above is what you need.
