### ISSUE TITLE
open a new branch for gatsby@v2

### ISSUE THREAD

**Issue by xyy94813** [bskimball/gatsby-plugin-antd#11]
Gatsby v2 is developing.
And many gatsby plugin has supported gatsby v2. 
Can you open a new branch to support the new version of gatsby? 
I am trying to support new version. 

> https://github.com/xyy94813/gatsby-plugin-antd

**Comment by Jaikant** [comment]
@xyy94813 Thanks for the update. I had to create a plugin directory and use your code to make it work with v2. It would be awesome to have your changes merged or a separate package if needed, so I do not have to maintain the code within my repo.

**Comment by bskimball** [comment]
I created a branch for v2 @xyy94813 I just used your code. Would you like contributor access?

**Comment by xyy94813** [comment]
contributor access? it is sounds great. @bskimball 

I am not sure if my code is valid when using `less`. it needs to be tested

**Comment by bskimball** [comment]
@xyy94813 I just sent you an invite.
