### ISSUE TITLE
Issues encountered trying to setup gatsby-plugin-antd

### ISSUE THREAD

**Issue by viccooper142** [bskimball/gatsby-plugin-antd#18]
Hi @bskimball 

I'm new to Gatsby and Antd and I ran into quite a few challenges trying to get this plugin working. Perhaps you could make some changes or additions to your documentation to help newbies based on what I discovered?

Steps taken:
```yarn add gatsby-plugin-antd```
(I'm using yarn because another plugin I installed for AWS needed it. npm install would do the same.)

Included the gatsby-plugin-antd plugin in my gatsby-config.js file with the option of using less because most of the Antd components use it as part of the [customize theme options](https://ant.design/docs/react/customize-theme).

```javascript
plugins: [
  {
      resolve: 'gatsby-plugin-antd',
      options: {
        style: true
      }
  }
]
```
After running ```gatsby develop```
```javascript
error  in ./node_modules/antd/lib/button/style/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../../style/themes/default';
```
I made an assumption that I missed something in the directions so I spent a lot of time trying to decypher the [Import on Demand directions](https://ant.design/docs/react/getting-started#Import-on-Demand)

Got very confused about the instructions to modify \.babelrc or babel-loader.
Finally realized that this plugin and Gatsby handles all changes to babel and webpack using it's own config file (duh) and that is why I cannot find \.babelrc or babel-loader anywhere.

Also tried adding less and less-loader using yarn but this does not work. Instead I need to use the [gatsby-plugin-less]( https://www.gatsbyjs.org/packages/gatsby-plugin-less/?=less)

Once I installed that and added it to my gatsby-config.js and ran gatsby develop, I get a new error:
```javascript
 error  in ./node_modules/antd/lib/button/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
```
Followed [the link](https://github.com/ant-design/ant-motion/issues/44) which is in Chinese. Right clicked on the page in Chrome and had Goggle AI translate it for me. Seems that less loader was changed for security reasons to turn off inline JavaScript and it needs to be turned on again for AntD.
[This link](https://github.com/gatsbyjs/gatsby/issues/6252) offered the solution for Gatsby

Added this code to my gatsby-config.js
```javascript
plugins: [
    {
      resolve: `gatsby-plugin-less`,
      options: {
        javascriptEnabled: true,
        modifyVars: {
          'primary-color': '#BADA55'
        }
      }
    }
  ]
```
And finally! it works. Not so wild about the new green color ```modifyVars: {'primary-color': '#BADA55'}``` but now I know how to change it.

Thank you for all your work on this plugin!

**Comment by kunalkapoor** [comment]
Newer versions of Less have different options settings. The following code will work for newer versions.
```
module.exports = {
  /* Your site config here */
  plugins: [
    {
        resolve: `gatsby-plugin-less`,
        options: {
            lessOptions: {
                javascriptEnabled: true,
            }
        }
    }
  ],
}
```

**Comment by ruoduan-hub** [comment]
> Hi @bskimball
> 
> I'm new to Gatsby and Antd and I ran into quite a few challenges trying to get this plugin working. Perhaps you could make some changes or additions to your documentation to help newbies based on what I discovered?
> 
> Steps taken:
> `yarn add gatsby-plugin-antd`
> (I'm using yarn because another plugin I installed for AWS needed it. npm install would do the same.)
> 
> Included the gatsby-plugin-antd plugin in my gatsby-config.js file with the option of using less because most of the Antd components use it as part of the [customize theme options](https://ant.design/docs/react/customize-theme).
> 
> ```js
> plugins: [
>   {
>       resolve: 'gatsby-plugin-antd',
>       options: {
>         style: true
>       }
>   }
> ]
> ```
> 
> After running `gatsby develop`
> 
> ```js
> error  in ./node_modules/antd/lib/button/style/index.less
> Module parse failed: Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> > @import '../../style/themes/default';
> ```
> 
> I made an assumption that I missed something in the directions so I spent a lot of time trying to decypher the [Import on Demand directions](https://ant.design/docs/react/getting-started#Import-on-Demand)
> 
> Got very confused about the instructions to modify .babelrc or babel-loader.
> Finally realized that this plugin and Gatsby handles all changes to babel and webpack using it's own config file (duh) and that is why I cannot find .babelrc or babel-loader anywhere.
> 
> Also tried adding less and less-loader using yarn but this does not work. Instead I need to use the [gatsby-plugin-less](https://www.gatsbyjs.org/packages/gatsby-plugin-less/?=less)
> 
> Once I installed that and added it to my gatsby-config.js and ran gatsby develop, I get a new error:
> 
> ```js
>  error  in ./node_modules/antd/lib/button/style/index.less
> 
> Module build failed (from ./node_modules/less-loader/dist/cjs.js):
> 
> // https://github.com/ant-design/ant-motion/issues/44
> .bezierEasingMixin();
> ^
> Inline JavaScript is not enabled. Is it set in your options?
> ```
> 
> Followed [the link](https://github.com/ant-design/ant-motion/issues/44) which is in Chinese. Right clicked on the page in Chrome and had Goggle AI translate it for me. Seems that less loader was changed for security reasons to turn off inline JavaScript and it needs to be turned on again for AntD.
> [This link](https://github.com/gatsbyjs/gatsby/issues/6252) offered the solution for Gatsby
> 
> Added this code to my gatsby-config.js
> 
> ```js
> plugins: [
>     {
>       resolve: `gatsby-plugin-less`,
>       options: {
>         javascriptEnabled: true,
>         modifyVars: {
>           'primary-color': '#BADA55'
>         }
>       }
>     }
>   ]
> ```
> 
> And finally! it works. Not so wild about the new green color `modifyVars: {'primary-color': '#BADA55'}` but now I know how to change it.
> 
> Thank you for all your work on this plugin!

# HI !
> I also encountered the same problem, but my setting like this has no effect
