### ISSUE TITLE
Does not seem to be working anymore

### ISSUE THREAD

**Issue by Aditya94A** [bskimball/gatsby-plugin-antd#19]
A simple 

```
<div style={{ width: 300, border: "1px solid #d9d9d9", borderRadius: 4 }}>
    <Input placeholder="Basic usage"/>
    <Calendar fullscreen={false}/>
  </div>
```

Produces the following 

![image](https://user-images.githubusercontent.com/13274079/68088738-f53d8300-fe87-11e9-944d-b6a57d29e9a3.png)

The CSS injection doesn't seem to be working correctly or there's some conflicting classes.

**Comment by bskimball** [comment]
This plugin had not previously indicated the libraryDirectory. I have changed that to match what is in the docs. The update has been pushed to npm. Please update to 2.1.0 and see if the issue persists. If it persists, you may need to open an issue with antd itself.

This plugin just implements Ant Design on demand as published in their documentation https://ant.design/docs/react/introduce#Use-modularized-antd
