### ISSUE TITLE
Replace moment.js with Day.js as suggested in antd docs

### ISSUE THREAD

**Issue by codewaseem** [bskimball/gatsby-plugin-antd#21]
I would like to replace moment.js with day.js for smaller bundle sizes. 

Resources:
https://github.com/ant-design/antd-dayjs-webpack-plugin
https://ant.design/docs/react/getting-started#Replace-momentjs-to-Day.js

**Comment by bskimball** [comment]
Moment was deprecated

**Comment by plotka** [comment]
Hi @codewaseem did you find a solution? I also want to replace moment.js
