### ISSUE TITLE
Datepicker styling is broken 

### ISSUE THREAD

**Issue by djoksimo** [bskimball/gatsby-plugin-antd#22]
**Describe the bug**

The antd `<DatePicker />` component styling is broken and does not match the ant design docs example. https://ant.design/components/date-picker/#header.

I've tried out a few different components and they seem to be styled correctly. I was only able to reproduce this bug with the DatePicker

**To Reproduce**

```jsx
import { DatePicker } from "antd";

...


return (
  <>
    DatePicker onChange={() => {}} />
  </>
)
```

**Expected behavior**

Should look like:
![image](https://user-images.githubusercontent.com/32694765/82131886-0278ea00-97a8-11ea-858e-02671fc8aea3.png)

**Screenshots**

This is what it actually looks like
![image](https://user-images.githubusercontent.com/32694765/82131878-ed03c000-97a7-11ea-8ce0-8999642e3798.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version v81.0.4044.138 

**Additional context**

My `gatsby-config`:

```js
   {
      resolve: "gatsby-plugin-antd",
      options: {
        style: true,
      },
    },
    {
      resolve: "gatsby-plugin-less",
      options: {
        javascriptEnabled: true,
      },
    },
```

My dependencies:

```
"antd": "^4.2.3",
"gatsby": "^2.21.11",
"gatsby-plugin-antd": "^2.2.0",
"gatsby-plugin-less": "^3.2.1",
```

**Comment by omar-bz** [comment]
@djoksimo the broken style is due to gatsby's layout style (layout.css), I find that removing the blocks targeting "table", "td" & "th" fixes the issue.
