### ISSUE TITLE
No matching version found for babel-plugin-import@^1.7.03

### ISSUE THREAD

**Issue by Jenny9502** [bskimball/gatsby-plugin-antd#6]
I failed to install your project,like this:
$ npm install gatsby-plugin-antd
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-plugin-import@^1.7.03
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby-plugin-antd'
npm ERR! notarget
 how to solve

**Comment by bskimball** [comment]
Looks like I may have to adjust my dependencies. I will update npm.

**Comment by bskimball** [comment]
NPM has been updated to the correct versions.
