### ISSUE TITLE
[v2] CSS is not loading. Maybe because of outdated api?

### ISSUE THREAD

**Issue by daydream05** [bskimball/gatsby-plugin-antd#9]
modifyBabelRC was refactored into onCreateBabelConfig for v2.

**Comment by bskimball** [comment]
I haven't checked out v2 yet. You're probably correct.

**Comment by bskimball** [comment]
I have created a branch for Gatsby v2

https://github.com/bskimball/gatsby-plugin-antd/tree/v2

**Comment by alexedev** [comment]
@bskimball but 2.0.0 version of the plugin was not released in npm yet, right?

**Comment by kamontat** [comment]
I want this.

**Comment by bskimball** [comment]
Both versions are now on npm
```
for version 1
$ npm install --save gatsby-plugin-antd@^1.0.0

for version 2
$ npm install --save gatsby-plugin-antd@^2.0.0
```

**Comment by kamontat** [comment]
Did anyone try this?? Is it work??

**Comment by bskimball** [comment]
@kamontat it works. I had to install antd as well which is not in the instructions

```
$ npm install --save antd
```

**Comment by kamontat** [comment]
Since I use both `scss` and `typescript`. It didn’t work for me.

**Comment by bskimball** [comment]
I don't use typescript but it looks like typescript requires ts-import-plugin. 

https://ant.design/docs/react/use-in-typescript

We are using babel-plugin-import. 

I can look in to adding typescript but it may not happen soon. 

In the meantime you can import manually, or submit a PR.
